### ISSUE TITLE
Result should have a chain or then methed

### ISSUE THREAD

**Issue by skimmilk6877** [swan-io/boxed#10]
I plan use boxed in my cli project, but I find it lack this feature, so I turn to use fp-ts instead.

**Comment by skimmilk6877** [comment]
```rust
fn main() {
    if let Err(e) = catr::get_args().and_then(catr::run) {
        eprintln!("{}", e);
        std::process::exit(1);
    }
}

```

**Comment by skimmilk6877** [comment]
In rust, a result can use and_then,if result is ok, pipe line continue, and if result throw error, throw the error.

I think this is so useful method for result.

**Comment by bloodyowl** [comment]
What you are describing is the [flatMap](https://swan-io.github.io/boxed/result#flatmapf) function, which is available.

**Comment by skimmilk6877** [comment]
@bloodyowl thanks
