### ISSUE TITLE
`Result.get()` can't accept outside `Result.isOk` scope even if `Result.isError()` checked and return before.

### ISSUE THREAD

**Issue by TrungRueta** [swan-io/boxed#21]
```ts
const a = async () => {
       const createAcc = await Result.fromPromise(
		auth.createUser({
			displayName: name,
			email,
			emailVerified: false,
			password
		})
	);
	
  if (createAcc.isError()) return createAcc
// we should allow get value here because we catched error case and return before.
  const acc = createAcc.get()
}
```

Hi, i think this case is common, in functions, return error catched before get final result give cleaner code, if only check `isOk()` with a scope we will end up many nested `if`.

For now error show like this :

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/12226007/170818220-d7c85657-aedd-438a-8929-94367f1e51e9.png">

**Comment by bloodyowl** [comment]
Hi! Thanks for the report. This is known issue, we're currently investigating if we can manage to get a better DX for this while preserving other key features. 

I'll write down about the progress  in the coming days in this thread.

**Comment by drazik** [comment]
I have the same error in a case that looks similar. In my case, I am using an `Option` inside a `Result`. The goal is to represent something that can either be a `Some<string>` or a `None` or an error. See [this typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgJQKYGcCuAbGAaOAeTBmAgDs4BfOAMyghDgCIABdAdwENyBaMgPQAjCAA9UAE2YAoaQGMK6eEq4xUcALyJpcOsGyoAXCgw4YAOkIBrABTFSFcwDkKqADxKowcgHMAfDYAlIHSVLIqaua0+upaaFi4lrb2ZOTmAMqMqDbMABao2NgQzMGywLRwNhGoUTHmwOjWQXAAZC1w1bUG5j6oMEH16Jkg2cHaugrk6BDdRT5VMKo10d29-YE9fUEhYUA).

Is there any workaround to this?

**Comment by zoontek** [comment]
Hi @drazik ! I already fixed all of this in https://github.com/swan-io/boxed/pull/25
I'm just waiting for a peer review.

**Comment by zoontek** [comment]
@drazik @TrungRueta This is fixed in latest version, give it a try!
