### ISSUE TITLE
Package fails to install due to missing yarn dependency

### ISSUE THREAD

**Issue by hellos3b** [swan-io/boxed#30]
When trying to add this package to my project with pnpm, I am getting a yarn not found exception. This is because the prepare script is being ran on my machine after install 

```
 ERR_PNPM_PREPARE_PKG_FAILURE  not found: yarn
```

https://github.com/swan-io/boxed/blob/e951a0239f2034d9ee7ff416f10df7abd12d5620/package.json#L38

According to npm docs, the `npm prepare` script gets ran before publish but also after installing the package. If the purpose of the prepare script is to test & build the source files, maybe they can be added to `prepublishOnly`  instead?

Reference: https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-install

**Comment by zoontek** [comment]
Unfortunately, yarn doesn't support `prepublishOnly` lifecycle script.

**Comment by hellos3b** [comment]
Ah you're right, they don't. For yarn it looks like instead they recommed to use the [prepack](https://yarnpkg.com/advanced/lifecycle-scripts) lifecycle script for building/bundling.

https://yarnpkg.com/advanced/rulebook#packages-should-use-the-prepack-script-to-generate-dist-files-before-publishing

> **Packages should use the prepack script to generate dist files before publishing**

> **Why?** The original npm supported [many different scripts](https://docs.npmjs.com/misc/scripts). So much, in fact, that it became very difficult to know which script one would want to use in which context. In particular, the very subtle differences between the prepack, prepare, prepublish, and prepublish-only scripts led many to use the wrong script in the wrong context. For this reason, Yarn 2 deprecated most of the scripts and consolidated them around a restricted set of portable scripts.

> **Solution:** Always use the prepack script if you wish to generate dist artifacts before publishing your package. It will get called before calling yarn pack (which itself is called before calling yarn npm publish), when cloning your git repository as a git dependency, and any time you will run yarn prepack. As for prepublish, never use it with side effects - its only use should be to run tests before the publish step.

Maybe that will help? Would love to install this package for work but requiring yarn is a blocker
