### ISSUE TITLE
How do you deal if you want to handle results and async functions?

### ISSUE THREAD

**Issue by itstheandre** [swan-io/boxed#35]
is there such a thing as an async map? something that would, instead of returning `Result<Promise<true>>` to `Promise<Result<true>>`?

So that it would be obvious? 

I do not know, if it is possible but would be great!

thanks,

**Comment by bloodyowl** [comment]
could you elaborate on this? not sure I'm getting your question

**Comment by itstheandre** [comment]
Sure. Maybe I am just being a little unknowledgeable, but from what I am seeing, I would like to know how to do something like this:

```ts
const user = getUser() // Result<User, Error>

const getDbUserInfo = user.map(async u => getInfo(u))

```

as far as i see, right now the last variable is a `Result<Promise<SomeData>, Error>`. My question is, how would anyone handle this? Is the goal that  , from here, we should check the error and then just await the `.value` or the `.get()` ?

**Comment by bloodyowl** [comment]
you can use:

```ts
Future.value(getUser())
  .flatMapOk(user => Future.fromPromise(getInfo(user)))
```

which gives you a `Future<UserInfo, Error>`.

you can `await` it or convert back to a promise using `.toPromise()` 😊

**Comment by itstheandre** [comment]
hey @bloodyowl if `getInfo` also returned `Promise<Result<x, unknown>>` the result would be something like `Future<Result<Result>>`. Is there a way to eventually flatten?

**Comment by bloodyowl** [comment]
you can use the following to flatten nested results:

```ts
result.flatMap(x => x)
```
