### ISSUE TITLE
Error reported when using in parcel

### ISSUE THREAD

**Issue by IMLaoJI** [swan-io/boxed#4]
Do I need to configure parcel, I'm new to parcel
![image](https://user-images.githubusercontent.com/16029951/160288979-e2bc7191-e46b-4dd0-8a40-16de0b8967f3.png)

**Comment by zoontek** [comment]
@IMLaoJI Hi! It seems to be an issue with Parcel: https://github.com/parcel-bundler/parcel/issues/7610

**Comment by IMLaoJI** [comment]
> @IMLaoJI Hi! It seems to be an issue with Parcel: [parcel-bundler/parcel#7610](https://github.com/parcel-bundler/parcel/issues/7610)
Thank you very much, I know where the problem lies, by the way, your boxed tool library is very good, I can't wait to use it in the project, I hope to add more good tools!

**Comment by bloodyowl** [comment]
Thanks! Hope the library is useful to you.

Closing this as is a Parcel issue.
