### ISSUE TITLE
Result from serialized json

### ISSUE THREAD

**Issue by Lilja** [swan-io/boxed#47]
Hi! I watched your talk on nordicjs, it was inspiring. I've been using it for some of my vue projects.

I'm currently using it both on the server and client through tRPC. When tRPC serializes the result, which from what I've understood is a class with specific methods, it creates a json struct which it sends down to the client.

Therefore, I would need to turn something like `{"tag": "Ok", "value: "[...]"}` into a `Result` class on the client, if that makes sense. Do you think there's a valid use case for this?

**Comment by zoontek** [comment]
Hi! Isn't https://swan-io.github.io/boxed/serializer what you are looking for?

**Comment by Lilja** [comment]
Thanks, missed that!
