### ISSUE TITLE
ts-pattern matching tuple where one value is an option is not working

### ISSUE THREAD

**Issue by momentiris** [swan-io/boxed#56]
Hey and thanks for a great library.
I just stumbled across what I think is a bug. I'm not 100% sure if this belongs here or at ts-pattern's repo but my repro suggests that it could be here (if I'm not entirely mistaken and the error is on my end.. :)

I want to pattern match on a tuple where one of the values is an `Option`. Below is an example that highlights the problem:

```ts
const withOption = match(Option.Some("foo")).with(
  Option.P.Some(P.select()),
  (val) => val // val: string
);

const withoutOptionTuple = match([{ type: "a" }, { type: "baz" }]).with(
  [{ type: "a" }, { type: "baz" }],
  ([a, b]) => [a, b] // a: { type: string }, b: { type: string }
);

const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
  [{ type: "a" }, Option.P.Some(P.select())],
  ([a, b]) => [a, b] // a: string, b: string
);
```

The last example says the parameter to the callback function is a string even if I don't destructure:

```ts
const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
  [{ type: "a" }, Option.P.Some(P.select())],
  (val) => val // val: string
);
```

Which kind of leads me to believe this might be a TS issue unrelated to your library.. but idk 🤷 

Do you see anything weird here too?

sandbox: https://codesandbox.io/s/late-haze-4rt5pg?file=/src/index.ts

**Comment by zoontek** [comment]
@momentiris Hi 👋

That's actually normal. As you are using `P.select()`, you ask `ts-pattern`: "If this branch match, extract the value that's here".

If you want to get the whole tuple, use this instead:

```ts
const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
  [{ type: "a" }, Option.P.Some(P.string)],
  ([a, b]) => [a, b.get()] // value is [{ type: string }, Some<string>], you can use b.get() directly
);
```

**Comment by momentiris** [comment]
> @momentiris Hi 👋
> 
> That's actually normal. As you are using `P.select()`, you ask `ts-pattern`: "If this branch match, extract the value that's here".
> 
> If you want to get the whole tuple, use this instead:
> 
> ```ts
> const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
>   [{ type: "a" }, Option.P.Some(P.string)], // we don't use P.select() but P.string here - it would also work with P.any
>   ([a, b]) => [a, b.get()] // value is [{ type: string }, Some<string>]: you can use b.get() directly
> );
> ```

Ahh I see! So it's not "selecting" the value into whatever position in the arbitrary data structure that I match on, but rather just "overriding" and selecting the value into the callback?

Thanks for that!

**Comment by zoontek** [comment]
@momentiris Exactly! You can also `select` multiple values and name it if you want 🙂!

```ts
import { Option } from "@swan-io/boxed";
import { match, P } from "ts-pattern";

const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
  [
    { type: P.select("type", P.string) }, // select "type" if it's a string
    Option.P.Some(P.select("value")) // select "value" if it's a Some<*>
  ],
  ({ type, value }) => ({ type, value }) // { type: string, value: string }
);
```

**Comment by momentiris** [comment]
Do you know why my first examples resulted in the first tuple argument 'resolved' to string too?

**Comment by momentiris** [comment]
Do you know why my incorrect approach resulted in the first tuple value 'resolved' to string, while also 'resolving' to string when not destructured?

```ts
const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
  [{ type: "a" }, Option.P.Some(P.select())],
  ([a, b]) => [a, b] // a: string, b: string
);
```
vs
```ts
const withOptionTuple = match([{ type: "a" }, Option.Some("bar")]).with(
  [{ type: "a" }, Option.P.Some(P.select())],
  (val) => val // val: string
);
```

**Comment by zoontek** [comment]
@momentiris Yeah, because it resolves to `string` (the `Some` value), and in JS string are destructurables:

```ts
const [a, b] = "test"; // a: string, b: string
```

**Comment by momentiris** [comment]
Haha, yeah of course. Now I understand. Thanks for pointing me in the right direction and also giving me a valuable lesson! :heart: 🙈

**Comment by zoontek** [comment]
@momentiris No problem, enjoy using boxed! :)
