### ISSUE TITLE
How to detect is a Future or Result is instanceof Future or Result

### ISSUE THREAD

**Issue by thuringia** [swan-io/boxed#57]
Hi,

thanks for building this library, so far it has been my team's life much easier!
For performance tracking I have to find out, how long it takes for a function to execute. That part is not the problem, unfortunately our code is a mixture of return values, and tracking `Future`, `Result` and `Promise` requires type-specific code.

It looks like using `instanceof` cannot be used here, as can be seen in this [Replit](https://replit.com/@thuringia/ForcefulDeepskyblueBundledsoftware#index.js). So I created these type guards, which while serviceable are rather hacky:
```ts
type AnyFunction = (...args: any[]) => any;

const isFuture = (x: unknown): x is Future<any> =>
  Reflect.has((x as AnyFunction).constructor, "value");

const isResult = (x: unknown): x is Result<any, any> =>
  Reflect.has((x as AnyFunction).constructor, "isOk");
```

Is there a better solution for this?

Thank you for any help or tips and I hope you have a great day!
Robert

**Comment by zoontek** [comment]
@thuringia Hi!

As you might know, we highly recommend [`ts-pattern`](https://github.com/gvergnaud/ts-pattern), a super cool 1kb pattern matching library. Boxed even [offers interop with it](https://swan-io.github.io/boxed/result#ts-pattern-interop).

This library also gives you `isMatching`, a nice util to create type guards.<br>I personally would use it like this:

```ts
import { Result } from "@swan-io/boxed";
import { isMatching } from "ts-pattern";

const x = Future.make(resolve => {
  const timeoutId = setTimeout(() => {
    resolve(0);
  }, 1000);

  return () => clearTimeout(timeoutId);
});

const y = Promise.resolve(1);
const z = Result.Ok(2);

// First, we grab a Future constructor:
const { constructor } = Future.make(() => {});

// Then we create static patterns:
const FuturePattern = { constructor }; // match if value has an identical constructor
const PromisePattern = P.instanceOf(Promise); // match if value is an instance of Promise
const ResultPattern = P.union(Result.P.Ok(P._), Result.P.Error(P._)); // match if any of the Result provided patterns match

// Then we create type guards:
const isFuture = (value: unknown): value is Future<unknown> =>
  isMatching(FuturePattern, value);

const isPromise = (value: unknown): value is Promise<unknown> =>
  isMatching(PromisePattern, value);

const isResult = (value: unknown): value is Result<unknown, unknown> =>
  isMatching(ResultPattern, value);

// All good!
console.log("Future checks");
console.log("constructor name", isFuture(x));

console.log("\nPromise checks");
console.log("instanceof", isPromise(y));

console.log("\nResult checks");
console.log("z has Result#isOk", isResult(z));

// value could be a Future | Promise | Result
const value = Math.random() > 0.5 ? x : Math.random() > 0.5 ? y : z;

if (isFuture(value)) {
  value; // type guard works!
}
if (isPromise(value)) {
  value; // type guard works!
}
if (isResult(value)) {
  value; // type guard works!
}
```

**Comment by thuringia** [comment]
@zoontek Using the whole constructor object is a much better idea.
This is very elegant with `ts-pattern` as well. We already are heavy users of `ts-pattern`, so that approach is right up our alley. Thanks for that tip!

I think shipping type guards as part of the library is an excellent idea. I can create a PR for this if you want, including additional ones like `isDeferred` or `isOption`. The biggest question here is, if they should use `ts-pattern` here, as that would introduce a hard dependency, instead of just interop.

**Comment by bloodyowl** [comment]
v1.1.0 includes the following guards:

- `Option.isOption`
- `Result.isResult`
- `AsyncData.isAsyncData`
- `Future.isFuture`
