### ISSUE TITLE
ts-pattern interop with `Option<boolean>` is not exhaustive

### ISSUE THREAD

**Issue by runeh** [swan-io/boxed#62]
I'm trying to match on the contents of an `Option<boolean>` with patterns for `Some<true>`, `Some<false>` and `None`, but ts-pattern gives a `NonExhaustiveError`.

Code below, and in this sandbox: https://codesandbox.io/s/vigilant-rhodes-w5mgy4?file=/src/index.ts

```
import { Option } from '@swan-io/boxed';
import { match } from 'ts-pattern';

const exists: Option<boolean> = Option.Some(true);

const booleanMatch = match(exists)
  .with(Option.P.Some(true), () => 'yes')
  .with(Option.P.Some(false), () => 'no')
  .with(Option.P.None, () => 'maybe')
  // error here:  NonExhaustiveError<Some<boolean>>
  .exhaustive(); 
```

Not sure if this is expected to work or not, I might be confused about the matching of `Some` objects. . It does work as expected if I use an `Option<'yes' | 'no'>`, so seems to be something about boolean not being narrowed? Could be in ts-pattern, but I thought I'd start here.

Apart from this, really enjoying boxed 👍

**Comment by zoontek** [comment]
@runeh That's because `true` and `false` in your branches are not of type `true` and `false`, but of type `boolean`. `true` and `false` is only their value. To enforce `true` to have a type `true` (and same for `false`), use `as const`:

```ts
import { Option } from "@swan-io/boxed";
import { match } from "ts-pattern";

const exists: Option<boolean> = Option.Some(true);

const booleanMatch = match(exists)
  .with(Option.P.Some(true as const), () => "yes")
  .with(Option.P.Some(false as const), () => "no")
  .with(Option.P.None, () => "maybe")
  .exhaustive();
```

**Comment by zoontek** [comment]
Actually, it would makes sense for boxed to use [const type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) for matching, removing the need for `as const` in such cases.

This means a new major version, as it drops support for TS < 5.

**Comment by zoontek** [comment]
@runeh [PR is opened here](https://github.com/swan-io/boxed/pull/63)

**Comment by zoontek** [comment]
Boxed v2 has been published with this change 🎉

**Comment by runeh** [comment]
> @runeh Boxed v2 has been published with this change 🎉

Thanks!
