### ISSUE TITLE
Why do you have a peerDependency on typescript?

### ISSUE THREAD

**Issue by blowery** [swan-io/boxed#73]
Howdy,

With 5.x, you've added a `peerDependency` on `typescript > 5`. That forces anyone who uses swan with yarn to declare a full dependency (not a devDependency) on typescript in projects that use boxed. Was that intentional? Do you really require typescript as a peer dependency at runtime?

Poking through the codebase, I don't see any imports from typescript in the src folder, so it doesn't seem so. Is this primarily to communicate that boxed requires at least typescript 5?

Would you consider changing it to a `devDependency` for boxed? Sadly there's no way to declare a peer-dev-dependency...

**Comment by zoontek** [comment]
@blowery This should to it: https://github.com/swan-io/boxed/pull/74
